name: issues and pull request workflow automation
run-name: ${{ github.actor }} has ignited ${{ github.workflow }}
true:
  issues:
    types:
    - opened
    - reopened
    - closed
    - labeled
    - unlabeled
    - assigned
    - unassigned
  pull_request:
    types:
    - opened
    - reopened
    - closed
    - labeled
    - unlabeled
    - review_requested
    - review_request_removed
    - assigned
    - unassigned
env:
  add: "Add \u2795"
  backend: "Backend \u2699\uFE0F"
  backlog: "Backlog \U0001F4DC"
  bugfix: "BugFix \U0001F41B"
  chore: "Chore \U0001F477\u200D\u2642\uFE0F"
  design: "Design \U0001F3A8"
  docs: "Docs \U0001F4DD"
  done: "Done \u2714\uFE0F"
  feat: "Feat \U0001F195"
  frontend: "Frontend \U0001F5A5\uFE0F"
  gh_app_id: ${{ secrets.APP_ID }}
  gh_app_installation_id: ${{ secrets.APP_INSTALLATION_ID }}
  gh_app_key: ${{ secrets.APP_SECRET_KEY }}
  in_progress: "In Progress \U0001F6A7"
  leduble: LeDuble/labeler@master
  leonsteinhaeuser: leonsteinhaeuser/project-beta-automations@v2.0.1
  organization_name: VirittamoHelsinki
  project_number: '21'
  ready_for_review: "Ready for Review \U0001F50D"
  refactor: "Refactor \U0001F501"
  review_requested: "Review Requested \U0001F50D"
  style: "Style \U0001F58C\uFE0F"
  test: "Test \u2611\uFE0F"
  un_assigned: "Unassigned \u2755"
  un_labeled: "Unlabeled \u2757"
  unassigned: "Unassigned \u2755"
  unlabeled: "Unlabeled \u2757"
jobs:
  issue_assigned:
    env:
      action_id: assigned or unassigned
      job_id: issue assigned or unassigned
      trigger_id: issues
    if: ${{ github.event_name == 'issues' && (github.event.action == 'assigned' ||
      github.event.action == 'unassigned') }}
    name: issue_assigned_unassigned
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The issue has been either assigned or unassigned. When the issue is
        assigned, it is then moved to the ${{ env.backlog }} status field in the project,
        and the ${{ env.backlog }} is added while the ${{ env.unassigned }} label
        is removed. When the issue is unassigned it is then moved to the ${{ env.unassigned
        }} status field in the project, and the ${{ env.unassigned }} label is added
        while the ${{ env.backlog }} label is removed."

        '
    - if: ${{ github.event.action == 'assigned' }}
      name: If assigned, adds ${{ env.backlog }} label and removes ${{ env.unassigned
        }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.backlog }}
        remove-labels: ${{ env.unassigned }}
    - name: If unassigned, adds ${{ env.unassigned }} label and removes ${{ env.backlog
        }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unassigned }}
        ignore-if-assigned: true
        remove-labels: ${{ env.backlog }}
  issue_closed:
    env:
      action_id: closed
      job_id: issue closed
      trigger_id: issues
    if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
    name: issue_closed
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The issue has been closed, moved to the ${{ env.done }} status field
        in the project, and the ${{ env.done }} was added while the ${{ env.backlog
        }}, ${{ env.in_progress }}, ${{ env.ready_for_review }} labels were removed"

        '
    - name: If closed, moves status value to ${{ env.done }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.done }}
    - name: If closed, adds ${{ env.done }} label and removes ${{ env.backlog }},
        ${{ env.in_progress }}, ${{ env.ready_for_review }} labels
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.done }}
        remove-labels: ${{ env.backlog }}, ${{ env.in_progress }}, ${{ env.ready_for_review
          }}
  issue_labeled:
    env:
      action_id: labeled
      job_id: issue labeled
      trigger_id: issues
    if: ${{ github.event_name == 'issues' && github.event.action == 'labeled' }}
    name: issue_labeled
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The issue is labeled and moved to either ${{ env.in_progress }}, ${{
        env.done }} or ${{ env.backlog }} status field in the project. The relevant
        status field is added and any unnecessary labels are removed. For example,
        if the ${{ env.backlog }} label is added, the issue is then moved to ${{ env.backlog
        }} status field in the project while the ${{ env.in_progress }}, ${{ env.done
        }} and ${{ env.ready_for_review }} labels are removed"

        '
    - if: "${{ github.event.label.name == 'In Progress \U0001F6A7' }}"
      name: moves status value to ${{ env.in_progress }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.in_progress }}
    - if: "${{ github.event.label.name == 'In Progress \U0001F6A7' }}"
      name: adds ${{ env.in_progress }} label and removes ${{ env.done }}, ${{ env.backlog
        }}, ${{ env.ready_for_review }} labels
      uses: LeDuble/labeler@master
      with:
        remove-labels: ${{ env.done }}, ${{ env.backlog }}, ${{ env.ready_for_review
          }}
    - if: "${{ github.event.label.name == 'Done \u2714\uFE0F' }}"
      name: moves status value to ${{ env.done }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.done }}
    - if: "${{ github.event.label.name == 'Done \u2714\uFE0F' }}"
      name: adds ${{ env.done }} label and removes ${{ env.in_progress }}, ${{ env.backlog
        }}, ${{ env.ready_for_review }} labels
      uses: LeDuble/labeler@master
      with:
        remove-labels: ${{ env.in_progress }}, ${{ env.backlog }}, ${{ env.ready_for_review
          }}
    - if: "${{ github.event.label.name == 'Backlog \U0001F4DC' }}"
      name: moves status value to ${{ env.backlog }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.backlog }}
    - if: "${{ github.event.label.name == 'Backlog \U0001F4DC' }}"
      name: adds ${{ env.backlog }} label and removes ${{ env.in_progress }}, ${{
        env.done }}, ${{ env.ready_for_review }} labels
      uses: LeDuble/labeler@master
      with:
        remove-labels: ${{ env.in_progress }}, ${{ env.done }}, ${{ env.ready_for_review
          }}
  issue_opened:
    env:
      action_id: opened or reopened
      job_id: issue opened or reopened
      trigger_id: issues
    if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action
      == 'reopened') }}
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The issue has been opened or reopened and moved to the ${{ env.backlog
        }} status field in the project. If no labels added, the ${{ env.unlabeled
        }} label is added. if it is unassigned, the ${{ env.unassigned }} label is
        added. When the issue is reopened, the ${{ env.backlog }} label is added and
        the ${{ env.done }} label is removed"

        '
    - name: moves status value to ${{ env.backlog }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.backlog }}
    - name: If unlabeled, adds {{ env.unlabeled }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unlabeled }}
        ignore-if-labeled: true
    - name: If unassigned, adds {{ env.unassigned }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unassigned }}
        ignore-if-assigned: true
    - name: If reopened, adds ${{ env.backlog }} label and removes ${{ env.done }}
        label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.backlog }}
        remove-labels: ${{ env.done }}
  pr_assigned:
    env:
      action_id: assigned or unassigned
      job_id: pr assigned or unassigned
      trigger_id: pull_request
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'assigned'
      || github.event.action == 'unassigned') }}
    name: pr_assigned_unassigned
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The pull request has been either assigned or unassigned. When the pull
        request is assigned, it is then moved to the ${{ env.ready_for_review }} status
        field in the project, and the ${{ env.ready_for_review }} is added while the
        ${{ env.unassigned }} label is removed. When the pull request is unassigned
        it is then moved to the ${{ env.unassigned }} status field in the project,
        and the ${{ env.unassigned }} label is added while the ${{ env.ready_for_review
        }} label is removed."

        '
    - if: ${{ github.event.action == 'assigned' }}
      name: if assigned, moves status value to ${{ env.backlog }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.ready_for_review }}
    - if: ${{ github.event.action == 'assigned' }}
      name: If assigned, adds ${{ env.ready_for_review }} label and removes ${{ env.unassigned
        }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.ready_for_review }}
        remove-labels: ${{ env.unassigned }}
    - name: If unassigned, adds ${{ env.unassigned }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unassigned }}
        ignore-if-assigned: true
  pr_closed:
    env:
      action_id: closed
      job_id: pull request closed
      trigger_id: pull_request
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed'
      }}
    name: pr_closed
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The pull request has been closed, moved to the ${{ env.done }} status
        field in the project, and the ${{ env.done }} was added while the ${{ env.backlog
        }}, ${{ env.in_progress }}, ${{ env.ready_for_review }} labels were removed"

        '
    - name: If closed, moves status value to ${{ env.done }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.done }}
    - name: If closed, adds ${{ env.done }} label and removes ${{ env.backlog }},
        ${{ env.in_progress }}, ${{ env.ready_for_review }} labels
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.done }}
        remove-labels: ${{ env.backlog }}, ${{ env.in_progress }}, ${{ env.ready_for_review
          }}
  pr_opened:
    env:
      action_id: opened or reopened
      job_id: pull request opened or reopened
      trigger_id: pull_request
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened'
      || github.event.action == 'reopened') }}
    name: pr_opened_or_reopened
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "The pull request has been opened or reopened and moved to the ${{ env.ready_for_review
        }} status field in the project. If no labels added, the ${{ env.unlabeled
        }} label is added. if it is unassigned, the ${{ env.unassigned }} label is
        added. When the pull request is reopened, the ${{ env.ready_for_review }}
        label is added and the ${{ env.done }} label is removed"

        '
    - name: moves status value to ${{ env.ready_for_review }}
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_app_ID: ${{ env.gh_app_id }}
        gh_app_installation_ID: ${{ env.gh_app_installation_id }}
        gh_app_secret_key: ${{ env.gh_app_key }}
        organization: ${{ env.organization_name }}
        project_id: ${{ env.project_number }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.ready_for_review }}
    - name: If unlabeled, adds {{ env.unlabeled }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unlabeled }}
        ignore-if-labeled: true
    - name: If unassigned, adds {{ env.unassigned }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.unassigned }}
        ignore-if-assigned: true
    - name: If reopened, adds ${{ env.backlog }} label and removes ${{ env.done }}
        label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.ready_for_review }}
        remove-labels: ${{ env.done }}
  pr_review_requested:
    env:
      action_id: review_requested or review_request_removed
      job_id: pull request review requested or review request removed
      trigger_id: pull_request
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'review_requested'
      || github.event.action == 'review_request_removed') }}
    name: pr_review_requested
    runs-on: ubuntu-latest
    steps:
    - name: summary (click to open)
      run: 'echo "The job id is: ${{ env.job_id }}"

        echo "The event id is: ${{ env.triggering_id }}"

        echo "The action id is: ${{ env.action_id }}"

        echo "Review requested or review request removed. Accordingly added either
        ${{ env.review_requested }} label or removed it"

        '
    - if: ${{ github.event.action == 'review_requested' }}
      name: If review requested, adds ${{ env.review_requested }} label
      uses: LeDuble/labeler@master
      with:
        add-labels: ${{ env.review_requested }}
    - if: ${{ github.event.action == 'review_request_removed' }}
      name: If review request removed, removes ${{ env.review_requested }} label
      uses: LeDuble/labeler@master
      with:
        remove-labels: ${{ env.review_requested }}
